name: Build CNOS ISO
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build ISO
        run: bash build-cnos-iso.sh
      - uses: actions/upload-artifact@v4
        with:
          name: CNOS-boot-iso
          path: CNOS-boot.iso
